sudo: required

services:
  - docker

env:
  - DOCKER_USER=ctudball
jobs:
  include:
    - stage: "Tests"
      name: "Run Mocha tests"
      install:
        - docker build -t $DOCKER_USER/hello-express .
      script:
        - docker run $DOCKER_USER/hello-express test