language: node_js

node_js:
  -node

jobs:
  include:
    - stage: "Tests"
      name: "Run Mocha tests"
      env:
        - NODE_ENV=development
      script: ./auto/test
    - stage: "deploy"
      name: "Deploy to Production"
      env:
        - NODE_ENV=production
      script: ./auto/deploy