sudo: required

services:
  - docker

jobs:
  include:
    - stage: "Tests"
      name: "Run Mocha tests"
      install:
        - docker build -t ctudball/hello-express .
      script:
        - docker run ctudball/hello-express test